/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as HdiRouteImport } from './routes/hdi'
import { Route as IncubacaoRouteImport } from './routes/incubacao'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConquistasRouteImport } from './routes/admin.conquistas'
import { Route as AdminEditaisRouteImport } from './routes/admin.editais'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminEventosRouteImport } from './routes/admin.eventos'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMensagensRouteImport } from './routes/admin.mensagens'
import { Route as AdminNoticiasRouteImport } from './routes/admin.noticias'
import { Route as AdminParceirosRouteImport } from './routes/admin.parceiros'
import { Route as AdminPerfisRouteImport } from './routes/admin.perfis'
import { Route as AdminPermissoesRouteImport } from './routes/admin.permissoes'
import { Route as AdminPremiacoesRouteImport } from './routes/admin.premiacoes'
import { Route as AdminResultadosRouteImport } from './routes/admin.resultados'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as EditaisIndexRouteImport } from './routes/editais.index'
import { Route as EditaisSlugRouteImport } from './routes/editais.$slug'
import { Route as EmpresasIndexRouteImport } from './routes/empresas.index'
import { Route as EmpresasSlugRouteImport } from './routes/empresas.$slug'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as ItncParceirosRouteImport } from './routes/itnc.parceiros'
import { Route as ItncSobreRouteImport } from './routes/itnc.sobre'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as AdminConfigGeralRouteImport } from './routes/admin.config.geral'
import { Route as AdminConfigInstitucionalRouteImport } from './routes/admin.config.institucional'
import { Route as AdminConfigRedesSociaisRouteImport } from './routes/admin.config.redes-sociais'
import { Route as AdminConfigSeoRouteImport } from './routes/admin.config.seo'
import { Route as AdminInstitucionalHdiRouteImport } from './routes/admin.institucional.hdi'
import { Route as AdminInstitucionalIncubacaoRouteImport } from './routes/admin.institucional.incubacao'
import { Route as AdminInstitucionalSobreRouteImport } from './routes/admin.institucional.sobre'
import { Route as AdminMidiaDocumentosRouteImport } from './routes/admin.midia.documentos'
import { Route as AdminMidiaImagensRouteImport } from './routes/admin.midia.imagens'
import { Route as AdminMidiaPdfsRouteImport } from './routes/admin.midia.pdfs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const HdiRoute = HdiRouteImport.update({
  id: '/hdi',
  path: '/hdi',
  getParentRoute: () => rootRouteImport,
} as any)
const IncubacaoRoute = IncubacaoRouteImport.update({
  id: '/incubacao',
  path: '/incubacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConquistasRoute = AdminConquistasRouteImport.update({
  id: '/admin/conquistas',
  path: '/admin/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditaisRoute = AdminEditaisRouteImport.update({
  id: '/admin/editais',
  path: '/admin/editais',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/admin/empresas',
  path: '/admin/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/admin/equipe',
  path: '/admin/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/admin/eventos',
  path: '/admin/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/admin/hero',
  path: '/admin/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMensagensRoute = AdminMensagensRouteImport.update({
  id: '/admin/mensagens',
  path: '/admin/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNoticiasRoute = AdminNoticiasRouteImport.update({
  id: '/admin/noticias',
  path: '/admin/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParceirosRoute = AdminParceirosRouteImport.update({
  id: '/admin/parceiros',
  path: '/admin/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPerfisRoute = AdminPerfisRouteImport.update({
  id: '/admin/perfis',
  path: '/admin/perfis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPermissoesRoute = AdminPermissoesRouteImport.update({
  id: '/admin/permissoes',
  path: '/admin/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPremiacoesRoute = AdminPremiacoesRouteImport.update({
  id: '/admin/premiacoes',
  path: '/admin/premiacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResultadosRoute = AdminResultadosRouteImport.update({
  id: '/admin/resultados',
  path: '/admin/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisIndexRoute = EditaisIndexRouteImport.update({
  id: '/editais/',
  path: '/editais/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditaisSlugRoute = EditaisSlugRouteImport.update({
  id: '/editais/$slug',
  path: '/editais/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIndexRoute = EmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasSlugRoute = EmpresasSlugRouteImport.update({
  id: '/empresas/$slug',
  path: '/empresas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ItncParceirosRoute = ItncParceirosRouteImport.update({
  id: '/itnc/parceiros',
  path: '/itnc/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ItncSobreRoute = ItncSobreRouteImport.update({
  id: '/itnc/sobre',
  path: '/itnc/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigGeralRoute = AdminConfigGeralRouteImport.update({
  id: '/admin/config/geral',
  path: '/admin/config/geral',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigInstitucionalRoute =
  AdminConfigInstitucionalRouteImport.update({
    id: '/admin/config/institucional',
    path: '/admin/config/institucional',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminConfigRedesSociaisRoute = AdminConfigRedesSociaisRouteImport.update({
  id: '/admin/config/redes-sociais',
  path: '/admin/config/redes-sociais',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigSeoRoute = AdminConfigSeoRouteImport.update({
  id: '/admin/config/seo',
  path: '/admin/config/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstitucionalHdiRoute = AdminInstitucionalHdiRouteImport.update({
  id: '/admin/institucional/hdi',
  path: '/admin/institucional/hdi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstitucionalIncubacaoRoute =
  AdminInstitucionalIncubacaoRouteImport.update({
    id: '/admin/institucional/incubacao',
    path: '/admin/institucional/incubacao',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminInstitucionalSobreRoute = AdminInstitucionalSobreRouteImport.update({
  id: '/admin/institucional/sobre',
  path: '/admin/institucional/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMidiaDocumentosRoute = AdminMidiaDocumentosRouteImport.update({
  id: '/admin/midia/documentos',
  path: '/admin/midia/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMidiaImagensRoute = AdminMidiaImagensRouteImport.update({
  id: '/admin/midia/imagens',
  path: '/admin/midia/imagens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMidiaPdfsRoute = AdminMidiaPdfsRouteImport.update({
  id: '/admin/midia/pdfs',
  path: '/admin/midia/pdfs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/hdi': typeof HdiRoute
  '/incubacao': typeof IncubacaoRoute
  '/resultados': typeof ResultadosRoute
  '/admin/conquistas': typeof AdminConquistasRoute
  '/admin/editais': typeof AdminEditaisRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/permissoes': typeof AdminPermissoesRoute
  '/admin/premiacoes': typeof AdminPremiacoesRoute
  '/admin/resultados': typeof AdminResultadosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/editais/$slug': typeof EditaisSlugRoute
  '/empresas/$slug': typeof EmpresasSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/itnc/parceiros': typeof ItncParceirosRoute
  '/itnc/sobre': typeof ItncSobreRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/editais/': typeof EditaisIndexRoute
  '/empresas/': typeof EmpresasIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/admin/config/geral': typeof AdminConfigGeralRoute
  '/admin/config/institucional': typeof AdminConfigInstitucionalRoute
  '/admin/config/redes-sociais': typeof AdminConfigRedesSociaisRoute
  '/admin/config/seo': typeof AdminConfigSeoRoute
  '/admin/institucional/hdi': typeof AdminInstitucionalHdiRoute
  '/admin/institucional/incubacao': typeof AdminInstitucionalIncubacaoRoute
  '/admin/institucional/sobre': typeof AdminInstitucionalSobreRoute
  '/admin/midia/documentos': typeof AdminMidiaDocumentosRoute
  '/admin/midia/imagens': typeof AdminMidiaImagensRoute
  '/admin/midia/pdfs': typeof AdminMidiaPdfsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/hdi': typeof HdiRoute
  '/incubacao': typeof IncubacaoRoute
  '/resultados': typeof ResultadosRoute
  '/admin/conquistas': typeof AdminConquistasRoute
  '/admin/editais': typeof AdminEditaisRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/permissoes': typeof AdminPermissoesRoute
  '/admin/premiacoes': typeof AdminPremiacoesRoute
  '/admin/resultados': typeof AdminResultadosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/editais/$slug': typeof EditaisSlugRoute
  '/empresas/$slug': typeof EmpresasSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/itnc/parceiros': typeof ItncParceirosRoute
  '/itnc/sobre': typeof ItncSobreRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/admin': typeof AdminIndexRoute
  '/editais': typeof EditaisIndexRoute
  '/empresas': typeof EmpresasIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/admin/config/geral': typeof AdminConfigGeralRoute
  '/admin/config/institucional': typeof AdminConfigInstitucionalRoute
  '/admin/config/redes-sociais': typeof AdminConfigRedesSociaisRoute
  '/admin/config/seo': typeof AdminConfigSeoRoute
  '/admin/institucional/hdi': typeof AdminInstitucionalHdiRoute
  '/admin/institucional/incubacao': typeof AdminInstitucionalIncubacaoRoute
  '/admin/institucional/sobre': typeof AdminInstitucionalSobreRoute
  '/admin/midia/documentos': typeof AdminMidiaDocumentosRoute
  '/admin/midia/imagens': typeof AdminMidiaImagensRoute
  '/admin/midia/pdfs': typeof AdminMidiaPdfsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/hdi': typeof HdiRoute
  '/incubacao': typeof IncubacaoRoute
  '/resultados': typeof ResultadosRoute
  '/admin/conquistas': typeof AdminConquistasRoute
  '/admin/editais': typeof AdminEditaisRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/noticias': typeof AdminNoticiasRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/perfis': typeof AdminPerfisRoute
  '/admin/permissoes': typeof AdminPermissoesRoute
  '/admin/premiacoes': typeof AdminPremiacoesRoute
  '/admin/resultados': typeof AdminResultadosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/editais/$slug': typeof EditaisSlugRoute
  '/empresas/$slug': typeof EmpresasSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/itnc/parceiros': typeof ItncParceirosRoute
  '/itnc/sobre': typeof ItncSobreRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/editais/': typeof EditaisIndexRoute
  '/empresas/': typeof EmpresasIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/admin/config/geral': typeof AdminConfigGeralRoute
  '/admin/config/institucional': typeof AdminConfigInstitucionalRoute
  '/admin/config/redes-sociais': typeof AdminConfigRedesSociaisRoute
  '/admin/config/seo': typeof AdminConfigSeoRoute
  '/admin/institucional/hdi': typeof AdminInstitucionalHdiRoute
  '/admin/institucional/incubacao': typeof AdminInstitucionalIncubacaoRoute
  '/admin/institucional/sobre': typeof AdminInstitucionalSobreRoute
  '/admin/midia/documentos': typeof AdminMidiaDocumentosRoute
  '/admin/midia/imagens': typeof AdminMidiaImagensRoute
  '/admin/midia/pdfs': typeof AdminMidiaPdfsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/hdi'
    | '/incubacao'
    | '/resultados'
    | '/admin/conquistas'
    | '/admin/editais'
    | '/admin/empresas'
    | '/admin/equipe'
    | '/admin/eventos'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/mensagens'
    | '/admin/noticias'
    | '/admin/parceiros'
    | '/admin/perfis'
    | '/admin/permissoes'
    | '/admin/premiacoes'
    | '/admin/resultados'
    | '/admin/usuarios'
    | '/editais/$slug'
    | '/empresas/$slug'
    | '/eventos/$slug'
    | '/itnc/parceiros'
    | '/itnc/sobre'
    | '/noticias/$slug'
    | '/admin/'
    | '/editais/'
    | '/empresas/'
    | '/eventos/'
    | '/noticias/'
    | '/admin/config/geral'
    | '/admin/config/institucional'
    | '/admin/config/redes-sociais'
    | '/admin/config/seo'
    | '/admin/institucional/hdi'
    | '/admin/institucional/incubacao'
    | '/admin/institucional/sobre'
    | '/admin/midia/documentos'
    | '/admin/midia/imagens'
    | '/admin/midia/pdfs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/hdi'
    | '/incubacao'
    | '/resultados'
    | '/admin/conquistas'
    | '/admin/editais'
    | '/admin/empresas'
    | '/admin/equipe'
    | '/admin/eventos'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/mensagens'
    | '/admin/noticias'
    | '/admin/parceiros'
    | '/admin/perfis'
    | '/admin/permissoes'
    | '/admin/premiacoes'
    | '/admin/resultados'
    | '/admin/usuarios'
    | '/editais/$slug'
    | '/empresas/$slug'
    | '/eventos/$slug'
    | '/itnc/parceiros'
    | '/itnc/sobre'
    | '/noticias/$slug'
    | '/admin'
    | '/editais'
    | '/empresas'
    | '/eventos'
    | '/noticias'
    | '/admin/config/geral'
    | '/admin/config/institucional'
    | '/admin/config/redes-sociais'
    | '/admin/config/seo'
    | '/admin/institucional/hdi'
    | '/admin/institucional/incubacao'
    | '/admin/institucional/sobre'
    | '/admin/midia/documentos'
    | '/admin/midia/imagens'
    | '/admin/midia/pdfs'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/hdi'
    | '/incubacao'
    | '/resultados'
    | '/admin/conquistas'
    | '/admin/editais'
    | '/admin/empresas'
    | '/admin/equipe'
    | '/admin/eventos'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/mensagens'
    | '/admin/noticias'
    | '/admin/parceiros'
    | '/admin/perfis'
    | '/admin/permissoes'
    | '/admin/premiacoes'
    | '/admin/resultados'
    | '/admin/usuarios'
    | '/editais/$slug'
    | '/empresas/$slug'
    | '/eventos/$slug'
    | '/itnc/parceiros'
    | '/itnc/sobre'
    | '/noticias/$slug'
    | '/admin/'
    | '/editais/'
    | '/empresas/'
    | '/eventos/'
    | '/noticias/'
    | '/admin/config/geral'
    | '/admin/config/institucional'
    | '/admin/config/redes-sociais'
    | '/admin/config/seo'
    | '/admin/institucional/hdi'
    | '/admin/institucional/incubacao'
    | '/admin/institucional/sobre'
    | '/admin/midia/documentos'
    | '/admin/midia/imagens'
    | '/admin/midia/pdfs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  HdiRoute: typeof HdiRoute
  IncubacaoRoute: typeof IncubacaoRoute
  ResultadosRoute: typeof ResultadosRoute
  AdminConquistasRoute: typeof AdminConquistasRoute
  AdminEditaisRoute: typeof AdminEditaisRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMensagensRoute: typeof AdminMensagensRoute
  AdminNoticiasRoute: typeof AdminNoticiasRoute
  AdminParceirosRoute: typeof AdminParceirosRoute
  AdminPerfisRoute: typeof AdminPerfisRoute
  AdminPermissoesRoute: typeof AdminPermissoesRoute
  AdminPremiacoesRoute: typeof AdminPremiacoesRoute
  AdminResultadosRoute: typeof AdminResultadosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  EditaisSlugRoute: typeof EditaisSlugRoute
  EmpresasSlugRoute: typeof EmpresasSlugRoute
  EventosSlugRoute: typeof EventosSlugRoute
  ItncParceirosRoute: typeof ItncParceirosRoute
  ItncSobreRoute: typeof ItncSobreRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EditaisIndexRoute: typeof EditaisIndexRoute
  EmpresasIndexRoute: typeof EmpresasIndexRoute
  EventosIndexRoute: typeof EventosIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  AdminConfigGeralRoute: typeof AdminConfigGeralRoute
  AdminConfigInstitucionalRoute: typeof AdminConfigInstitucionalRoute
  AdminConfigRedesSociaisRoute: typeof AdminConfigRedesSociaisRoute
  AdminConfigSeoRoute: typeof AdminConfigSeoRoute
  AdminInstitucionalHdiRoute: typeof AdminInstitucionalHdiRoute
  AdminInstitucionalIncubacaoRoute: typeof AdminInstitucionalIncubacaoRoute
  AdminInstitucionalSobreRoute: typeof AdminInstitucionalSobreRoute
  AdminMidiaDocumentosRoute: typeof AdminMidiaDocumentosRoute
  AdminMidiaImagensRoute: typeof AdminMidiaImagensRoute
  AdminMidiaPdfsRoute: typeof AdminMidiaPdfsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hdi': {
      id: '/hdi'
      path: '/hdi'
      fullPath: '/hdi'
      preLoaderRoute: typeof HdiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incubacao': {
      id: '/incubacao'
      path: '/incubacao'
      fullPath: '/incubacao'
      preLoaderRoute: typeof IncubacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conquistas': {
      id: '/admin/conquistas'
      path: '/admin/conquistas'
      fullPath: '/admin/conquistas'
      preLoaderRoute: typeof AdminConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editais': {
      id: '/admin/editais'
      path: '/admin/editais'
      fullPath: '/admin/editais'
      preLoaderRoute: typeof AdminEditaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/admin/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/admin/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/admin/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mensagens': {
      id: '/admin/mensagens'
      path: '/admin/mensagens'
      fullPath: '/admin/mensagens'
      preLoaderRoute: typeof AdminMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/noticias': {
      id: '/admin/noticias'
      path: '/admin/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AdminNoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parceiros': {
      id: '/admin/parceiros'
      path: '/admin/parceiros'
      fullPath: '/admin/parceiros'
      preLoaderRoute: typeof AdminParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/perfis': {
      id: '/admin/perfis'
      path: '/admin/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AdminPerfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/permissoes': {
      id: '/admin/permissoes'
      path: '/admin/permissoes'
      fullPath: '/admin/permissoes'
      preLoaderRoute: typeof AdminPermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/premiacoes': {
      id: '/admin/premiacoes'
      path: '/admin/premiacoes'
      fullPath: '/admin/premiacoes'
      preLoaderRoute: typeof AdminPremiacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/resultados': {
      id: '/admin/resultados'
      path: '/admin/resultados'
      fullPath: '/admin/resultados'
      preLoaderRoute: typeof AdminResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/': {
      id: '/editais/'
      path: '/editais'
      fullPath: '/editais/'
      preLoaderRoute: typeof EditaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editais/$slug': {
      id: '/editais/$slug'
      path: '/editais/$slug'
      fullPath: '/editais/$slug'
      preLoaderRoute: typeof EditaisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/': {
      id: '/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof EmpresasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/$slug': {
      id: '/empresas/$slug'
      path: '/empresas/$slug'
      fullPath: '/empresas/$slug'
      preLoaderRoute: typeof EmpresasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itnc/parceiros': {
      id: '/itnc/parceiros'
      path: '/itnc/parceiros'
      fullPath: '/itnc/parceiros'
      preLoaderRoute: typeof ItncParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itnc/sobre': {
      id: '/itnc/sobre'
      path: '/itnc/sobre'
      fullPath: '/itnc/sobre'
      preLoaderRoute: typeof ItncSobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config/geral': {
      id: '/admin/config/geral'
      path: '/admin/config/geral'
      fullPath: '/admin/config/geral'
      preLoaderRoute: typeof AdminConfigGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config/institucional': {
      id: '/admin/config/institucional'
      path: '/admin/config/institucional'
      fullPath: '/admin/config/institucional'
      preLoaderRoute: typeof AdminConfigInstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config/redes-sociais': {
      id: '/admin/config/redes-sociais'
      path: '/admin/config/redes-sociais'
      fullPath: '/admin/config/redes-sociais'
      preLoaderRoute: typeof AdminConfigRedesSociaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config/seo': {
      id: '/admin/config/seo'
      path: '/admin/config/seo'
      fullPath: '/admin/config/seo'
      preLoaderRoute: typeof AdminConfigSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/institucional/hdi': {
      id: '/admin/institucional/hdi'
      path: '/admin/institucional/hdi'
      fullPath: '/admin/institucional/hdi'
      preLoaderRoute: typeof AdminInstitucionalHdiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/institucional/incubacao': {
      id: '/admin/institucional/incubacao'
      path: '/admin/institucional/incubacao'
      fullPath: '/admin/institucional/incubacao'
      preLoaderRoute: typeof AdminInstitucionalIncubacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/institucional/sobre': {
      id: '/admin/institucional/sobre'
      path: '/admin/institucional/sobre'
      fullPath: '/admin/institucional/sobre'
      preLoaderRoute: typeof AdminInstitucionalSobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/midia/documentos': {
      id: '/admin/midia/documentos'
      path: '/admin/midia/documentos'
      fullPath: '/admin/midia/documentos'
      preLoaderRoute: typeof AdminMidiaDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/midia/imagens': {
      id: '/admin/midia/imagens'
      path: '/admin/midia/imagens'
      fullPath: '/admin/midia/imagens'
      preLoaderRoute: typeof AdminMidiaImagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/midia/pdfs': {
      id: '/admin/midia/pdfs'
      path: '/admin/midia/pdfs'
      fullPath: '/admin/midia/pdfs'
      preLoaderRoute: typeof AdminMidiaPdfsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  HdiRoute: HdiRoute,
  IncubacaoRoute: IncubacaoRoute,
  ResultadosRoute: ResultadosRoute,
  AdminConquistasRoute: AdminConquistasRoute,
  AdminEditaisRoute: AdminEditaisRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMensagensRoute: AdminMensagensRoute,
  AdminNoticiasRoute: AdminNoticiasRoute,
  AdminParceirosRoute: AdminParceirosRoute,
  AdminPerfisRoute: AdminPerfisRoute,
  AdminPermissoesRoute: AdminPermissoesRoute,
  AdminPremiacoesRoute: AdminPremiacoesRoute,
  AdminResultadosRoute: AdminResultadosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  EditaisSlugRoute: EditaisSlugRoute,
  EmpresasSlugRoute: EmpresasSlugRoute,
  EventosSlugRoute: EventosSlugRoute,
  ItncParceirosRoute: ItncParceirosRoute,
  ItncSobreRoute: ItncSobreRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  EditaisIndexRoute: EditaisIndexRoute,
  EmpresasIndexRoute: EmpresasIndexRoute,
  EventosIndexRoute: EventosIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  AdminConfigGeralRoute: AdminConfigGeralRoute,
  AdminConfigInstitucionalRoute: AdminConfigInstitucionalRoute,
  AdminConfigRedesSociaisRoute: AdminConfigRedesSociaisRoute,
  AdminConfigSeoRoute: AdminConfigSeoRoute,
  AdminInstitucionalHdiRoute: AdminInstitucionalHdiRoute,
  AdminInstitucionalIncubacaoRoute: AdminInstitucionalIncubacaoRoute,
  AdminInstitucionalSobreRoute: AdminInstitucionalSobreRoute,
  AdminMidiaDocumentosRoute: AdminMidiaDocumentosRoute,
  AdminMidiaImagensRoute: AdminMidiaImagensRoute,
  AdminMidiaPdfsRoute: AdminMidiaPdfsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
